name: Laravel

on:
  push:
    branches: [ production ]

jobs:
  production-deploy:
    name: deploy to sever
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd /home/piuwstud/sites/presensi-web
          git checkout production
          git pull
          composer install
          php artisan migrate --force
          php artisan config:cache
          php artisan view:cache
          php artisan route:cache

